# Generated by Django 4.0.1 on 2022-11-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ampliacao_ch',
            fields=[
                ('id_seq', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField(null=True)),
                ('anomes', models.IntegerField(null=True)),
                ('cod_servidor', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'ampliacao_ch',
            },
        ),
        migrations.CreateModel(
            name='Complemento',
            fields=[
                ('id_complemento', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField(null=True)),
                ('anomes', models.IntegerField(null=True)),
                ('codigo', models.IntegerField(null=True)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('salario_100H', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('num_dias', models.IntegerField(null=True)),
                ('participacao', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('vencimento_base', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('fundeb', models.CharField(default='N', max_length=1, null=True)),
            ],
            options={
                'db_table': 'complementos',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField()),
                ('id_evento_out', models.IntegerField(default=0)),
                ('evento', models.CharField(max_length=50)),
                ('evento_out', models.CharField(blank=True, max_length=50, null=True)),
                ('ampliacao_ch', models.CharField(default='N', max_length=1)),
                ('suporte', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('cancelado', models.CharField(default='N', max_length=1)),
                ('tipo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'eventos',
            },
        ),
        migrations.CreateModel(
            name='Folhaevento',
            fields=[
                ('id_folhaevento', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField(null=True)),
                ('anomes', models.IntegerField()),
                ('cod_servidor', models.IntegerField()),
                ('previdencia', models.CharField(max_length=6, null=True)),
                ('cl_orcamentaria', models.CharField(max_length=6, null=True)),
                ('id_evento', models.IntegerField(null=True)),
                ('tabela', models.IntegerField(null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
            ],
            options={
                'db_table': 'folhaeventos',
            },
        ),
        migrations.CreateModel(
            name='Folhames',
            fields=[
                ('id_folha', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField(null=True)),
                ('anomes', models.IntegerField()),
                ('cod_servidor', models.IntegerField()),
                ('cpf', models.CharField(max_length=11, null=True)),
                ('id_secretaria', models.IntegerField(null=True)),
                ('id_setor', models.IntegerField(null=True)),
                ('id_funcao', models.IntegerField(null=True)),
                ('id_vinculo', models.IntegerField(null=True)),
                ('previdencia', models.CharField(max_length=6, null=True)),
                ('num_dias', models.IntegerField(null=True)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('salario_100H', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('vencimento_base', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('participacao', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('fundeb', models.CharField(default='N', max_length=1, null=True)),
                ('carga_horaria', models.IntegerField(null=True)),
                ('data_criacao', models.DateTimeField(null=True)),
                ('ampliacao_ch', models.CharField(default='N', max_length=1, null=True)),
                ('suporte', models.CharField(default='N', max_length=1, null=True)),
                ('id_secretaria_origem', models.IntegerField(null=True)),
                ('id_setor_origem', models.IntegerField(null=True)),
                ('id_funcao_origem', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'folhames',
            },
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id_funcao', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField()),
                ('id_funcao_out', models.IntegerField(default=0)),
                ('funcao', models.CharField(max_length=100)),
                ('funcao_out', models.CharField(blank=True, max_length=100, null=True)),
                ('professor', models.CharField(default='N', max_length=1)),
                ('cancelado', models.CharField(default='N', max_length=1)),
                ('tipo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'funcoes',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField(null=True)),
                ('anomes', models.IntegerField(null=True)),
                ('codigo', models.IntegerField(null=True)),
                ('nome_servidor', models.CharField(max_length=100, null=True)),
                ('carga_horaria', models.IntegerField(null=True)),
                ('tipo_admissao', models.CharField(max_length=100, null=True)),
                ('data_admissao', models.CharField(max_length=10, null=True)),
                ('previdencia', models.CharField(max_length=100, null=True)),
                ('id_funcao', models.IntegerField(null=True)),
                ('id_setor', models.IntegerField(null=True)),
                ('id_secretaria', models.IntegerField(null=True)),
                ('id_secretaria_origem', models.IntegerField(null=True)),
                ('id_setor_origem', models.IntegerField(null=True)),
                ('id_funcao_origem', models.IntegerField(null=True)),
                ('fundeb', models.CharField(default='N', max_length=1)),
            ],
            options={
                'db_table': 'funcionarios',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField()),
                ('anomes', models.IntegerField()),
                ('codigo', models.IntegerField()),
                ('nome', models.CharField(max_length=150)),
                ('carga_horaria', models.IntegerField()),
                ('secretaria', models.CharField(max_length=150)),
                ('funcao', models.CharField(max_length=150)),
                ('num_dias', models.IntegerField()),
                ('valor_evento', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('num_mes', models.IntegerField()),
                ('cod_evento', models.IntegerField()),
                ('data_admissao', models.DateTimeField(null=True)),
                ('salario_base', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
            ],
            options={
                'db_table': 'informations',
            },
        ),
        migrations.CreateModel(
            name='LogErro',
            fields=[
                ('id_logerro', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField()),
                ('anomes', models.IntegerField(default=0)),
                ('numero_linha', models.IntegerField(null=True)),
                ('codigo', models.CharField(max_length=100, null=True)),
                ('observacao', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'logerro',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('municipio', models.CharField(max_length=100)),
                ('empresa', models.CharField(default='', max_length=100)),
                ('entidade', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'municipios',
            },
        ),
        migrations.CreateModel(
            name='Provento',
            fields=[
                ('id_provento', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField(null=True)),
                ('anomes', models.IntegerField(null=True)),
                ('codigo', models.IntegerField(null=True)),
                ('previdencia', models.CharField(default='', max_length=100, null=True)),
                ('tipo', models.IntegerField(null=True)),
                ('id_evento', models.IntegerField(null=True)),
                ('id_evento_origem', models.IntegerField(null=True)),
                ('tabela', models.IntegerField(null=True)),
                ('valor_evento', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('classificacao', models.CharField(max_length=15, null=True)),
                ('grupamento', models.CharField(default='S', max_length=1, null=True)),
                ('lixo', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'proventos',
            },
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_municipio', models.IntegerField()),
                ('anomes', models.IntegerField()),
                ('cod_servidor', models.IntegerField()),
                ('vencimento_base', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('carga_horaria', models.IntegerField()),
                ('num_dias', models.IntegerField()),
                ('carga_horaria_origem', models.IntegerField()),
                ('num_dias_origem', models.CharField(max_length=50, null=True)),
                ('salario_100h', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('participacao', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'db_table': 'salarios',
            },
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id_secretaria', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField()),
                ('id_secretaria_out', models.IntegerField(default=0)),
                ('secretaria', models.CharField(max_length=100)),
                ('secretaria_out', models.CharField(default='', max_length=100, null=True)),
                ('fundeb', models.CharField(default='N', max_length=1)),
                ('tipo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'secretarias',
            },
        ),
        migrations.CreateModel(
            name='SemCadastro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField()),
                ('tabela', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'semcadastros',
            },
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id_servidor', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('cod_servidor', models.IntegerField()),
                ('cpf', models.CharField(default='', max_length=20)),
                ('data_admissao', models.DateField(null=True)),
                ('ativo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'servidores',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id_setor', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField()),
                ('id_setor_out', models.IntegerField(default=0)),
                ('setor', models.CharField(max_length=100)),
                ('setor_out', models.CharField(blank=True, max_length=100, null=True)),
                ('fundeb', models.CharField(default='N', max_length=1)),
                ('tipo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'setores',
            },
        ),
        migrations.CreateModel(
            name='Setor_fundeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_municipio', models.IntegerField(null=True)),
                ('id_setor', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'setor_fundeb',
            },
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_municipio', models.IntegerField()),
                ('anomes', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('cod_servidor', models.IntegerField()),
                ('data_admissao', models.DateField(null=True)),
                ('natureza', models.IntegerField()),
                ('id_secretaria', models.IntegerField()),
                ('id_setor', models.IntegerField()),
                ('id_funcao', models.IntegerField()),
                ('id_evento', models.IntegerField()),
                ('id_secretaria_origem', models.IntegerField()),
                ('id_setor_origem', models.IntegerField()),
                ('id_funcao_origem', models.IntegerField()),
                ('id_evento_origem', models.IntegerField()),
                ('suporte', models.CharField(default='N', max_length=1)),
            ],
            options={
                'db_table': 'situacoes',
            },
        ),
        migrations.CreateModel(
            name='Suporte',
            fields=[
                ('id_seq', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField(null=True)),
                ('anomes', models.IntegerField(null=True)),
                ('cod_servidor', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'suportes',
            },
        ),
        migrations.CreateModel(
            name='Tab_salario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField()),
                ('id_funcao', models.IntegerField()),
                ('carga_horaria', models.IntegerField(null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'tab_salarios',
            },
        ),
        migrations.CreateModel(
            name='Tab_salarioch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField()),
                ('id_funcao', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('carga_horaria_errada', models.IntegerField(null=True)),
                ('carga_horaria_certa', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'tab_salariosch',
            },
        ),
        migrations.CreateModel(
            name='Tabela_salario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField()),
                ('id_funcao_origem', models.IntegerField()),
                ('salario_100h_int', models.IntegerField(default=0)),
                ('salario_100h_dec', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'tabela_salarios',
            },
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id_vinculo', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField()),
                ('vinculo', models.CharField(max_length=100)),
                ('grupo', models.CharField(default='N', max_length=1, null=True)),
            ],
            options={
                'db_table': 'vinculos',
            },
        ),
        migrations.CreateModel(
            name='XEvento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField()),
                ('tipo', models.CharField(max_length=100)),
                ('id_evento', models.IntegerField()),
            ],
            options={
                'db_table': 'xeventos',
            },
        ),
        migrations.AddIndex(
            model_name='xevento',
            index=models.Index(fields=['id_municipio', 'tipo'], name='xeventos_id_muni_d07099_idx'),
        ),
        migrations.AddConstraint(
            model_name='xevento',
            constraint=models.UniqueConstraint(fields=('id_municipio', 'tipo', 'id_evento'), name='unique_xevento'),
        ),
        migrations.AddConstraint(
            model_name='vinculo',
            constraint=models.UniqueConstraint(fields=('id_municipio', 'vinculo'), name='unique_vinculo'),
        ),
        migrations.AddIndex(
            model_name='suporte',
            index=models.Index(fields=['id_municipio', 'anomes', 'cod_servidor'], name='suportes_id_muni_03b0a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='setor_fundeb',
            constraint=models.UniqueConstraint(fields=('id_municipio', 'id_setor'), name='unique_setorfundebs'),
        ),
        migrations.AddConstraint(
            model_name='setor',
            constraint=models.UniqueConstraint(fields=('id_municipio', 'setor'), name='unique_setor'),
        ),
        migrations.AddIndex(
            model_name='servidor',
            index=models.Index(fields=['id_municipio'], name='servidores_id_muni_9234b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='servidor',
            constraint=models.UniqueConstraint(fields=('id_municipio', 'cod_servidor'), name='servidor_unique'),
        ),
        migrations.AddConstraint(
            model_name='secretaria',
            constraint=models.UniqueConstraint(fields=('id_municipio', 'secretaria'), name='unique_secretaria'),
        ),
        migrations.AddIndex(
            model_name='provento',
            index=models.Index(fields=['id_municipio', 'anomes', 'codigo'], name='proventos_id_muni_ea111b_idx'),
        ),
        migrations.AddIndex(
            model_name='funcionario',
            index=models.Index(fields=['id_municipio', 'anomes', 'codigo'], name='funcionario_id_muni_602431_idx'),
        ),
        migrations.AddConstraint(
            model_name='funcao',
            constraint=models.UniqueConstraint(fields=('id_municipio', 'funcao'), name='unique_funcao'),
        ),
        migrations.AddIndex(
            model_name='folhames',
            index=models.Index(fields=['id_municipio', 'anomes'], name='folhames_id_muni_e88aea_idx'),
        ),
        migrations.AddIndex(
            model_name='folhaevento',
            index=models.Index(fields=['id_municipio', 'anomes'], name='folhaevento_id_muni_ef07fe_idx'),
        ),
        migrations.AddIndex(
            model_name='complemento',
            index=models.Index(fields=['id_municipio', 'anomes', 'codigo'], name='complemento_id_muni_352868_idx'),
        ),
        migrations.AddIndex(
            model_name='ampliacao_ch',
            index=models.Index(fields=['id_municipio', 'anomes', 'cod_servidor'], name='ampliacao_c_id_muni_44954c_idx'),
        ),
    ]
