# Generated by Django 4.0.1 on 2022-11-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabela',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField()),
                ('grupo', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tabelas',
            },
        ),
        migrations.AddIndex(
            model_name='tabela',
            index=models.Index(fields=['id_municipio', 'grupo'], name='tabelas_id_muni_7c0bac_idx'),
        ),
    ]
