# Generated by Django 4.0.1 on 2022-11-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_tabela_tabela_tabelas_id_muni_7c0bac_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apelido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField()),
                ('grupo', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=150)),
                ('apelido', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'apelidos',
            },
        ),
        migrations.AddIndex(
            model_name='apelido',
            index=models.Index(fields=['id_municipio', 'grupo'], name='apelidos_id_muni_3a9b12_idx'),
        ),
    ]
