# Generated by Django 4.0.1 on 2022-11-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_apelido_apelido_apelidos_id_muni_3a9b12_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apelido',
        ),
    ]
