# Generated by Django 4.0.1 on 2022-11-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_apelido_apelido_apelidos_id_muni_a3d444_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apelido',
            name='secretaria',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='apelido',
            name='secretaria_out',
            field=models.CharField(max_length=120),
        ),
    ]
