# Generated by Django 4.0.1 on 2022-11-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_apelido_secretaria_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apelido',
        ),
    ]
