# Generated by Django 4.0.1 on 2022-11-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_apelido_apelido_apelidos_id_muni_b9fcb0_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complemento',
            name='participacao',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='folhames',
            name='participacao',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
