# Generated by Django 4.0.1 on 2022-11-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_complemento_participacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complemento',
            name='salario',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='complemento',
            name='salario_100H',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='folhames',
            name='salario',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='folhames',
            name='salario_100H',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
    ]
