# Generated by Django 4.0.1 on 2023-01-15 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_tab_salarioch_id_funcao_origem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tab_salarioch',
            name='id_funcao',
        ),
    ]
