# Generated by Django 4.0.1 on 2023-01-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_remove_tab_salarioch_id_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='folhames',
            name='vinculo',
            field=models.CharField(default='N', max_length=2),
        ),
    ]
