# Generated by Django 4.0.1 on 2023-02-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_alter_evento_evento_alter_evento_evento_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaHoraria',
            fields=[
                ('id_cargahoraria', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField()),
                ('cargah_origem', models.IntegerField()),
                ('cargah_convertida', models.IntegerField()),
            ],
            options={
                'db_table': 'cargahorarias',
            },
        ),
        migrations.AddIndex(
            model_name='cargahoraria',
            index=models.Index(fields=['id_municipio', 'cargah_origem'], name='cargahorari_id_muni_05d206_idx'),
        ),
    ]
