# Generated by Django 4.0.1 on 2023-03-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_cargahoraria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folhames',
            name='carga_horaria_origem',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='carga_horaria_origem',
            field=models.IntegerField(null=True),
        ),
    ]
