# Generated by Django 4.0.1 on 2023-03-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_documento_documento_documentos_id_muni_34e72c_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='ano',
            field=models.IntegerField(default=2000),
        ),
    ]
