# Generated by Django 4.0.1 on 2023-03-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_documento_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='folhames',
            name='grupo',
            field=models.CharField(default='N', max_length=2),
        ),
    ]
