# Generated by Django 4.0.1 on 2023-04-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_folhames_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='id_user',
            field=models.IntegerField(default=0),
        ),
    ]
